### ISSUE TITLE
Add correct responses to requests

### ISSUE THREAD

**Issue by bobvanluijt** [weaviate/weaviate-swagger#1]
Now successful response is always 200, this should be updated to be more suitable and include the not implemented response too.

List of responses: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

At least add / update 200 respones with: 201, 204, 501 (all should have this),

**Comment by johnciocoiu** [comment]
GET: 200 and 501
POST: 201 and 501
DELETE: 204 and 501
PUT/PATCH: 200 (updates in stead of creates, but is returning content so 200 and not 201 or 204) and 501
