### ISSUE TITLE
What to return on the GET /things-endpoint?

### ISSUE THREAD

**Issue by johnciocoiu** [weaviate/weaviate-swagger#101]
What do we want the things that will be the response of the GET /things-endpoint?
- All things, sorted on 'createdtime'?
- Just things of one type? (e.g. 'schema.org/Person'). Also sorted on 'createdtime'.

In case of the latter, we need to extend the swagger document.

**Comment by bobvanluijt** [comment]
Good question, return all in random order based on the request KEY.

Later we will implement sorting for this.

**Comment by johnciocoiu** [comment]
Could be found here: https://github.com/weaviate/weaviate/issues/172
