### ISSUE TITLE
Make new release of the API

### ISSUE THREAD

**Issue by johnciocoiu** [weaviate/weaviate-swagger#45]
Because of a fix in the Place ID (not UUID), a new server has to be made.

**Comment by johnciocoiu** [comment]
And several other fixes:
- https://github.com/weaviate/weaviate-swagger/issues/46
- https://github.com/weaviate/weaviate-swagger/issues/47

**Comment by johnciocoiu** [comment]
Please merge release into https://github.com/weaviate/weaviate/tree/feature/thing-templates

**Comment by bobvanluijt** [comment]
Done: https://github.com/weaviate/weaviate-swagger/releases/tag/v0.2.3
