### ISSUE TITLE
Do new release

### ISSUE THREAD

**Issue by johnciocoiu** [weaviate/weaviate-swagger#54]
After these issues are being closed:
- [x] https://github.com/weaviate/weaviate-swagger/issues/51
- [x] https://github.com/weaviate/weaviate-swagger/issues/52
- [x] https://github.com/weaviate/weaviate-swagger/issues/53
- [x] https://github.com/weaviate/weaviate-swagger/issues/55
- [x] https://github.com/weaviate/weaviate-swagger/issues/56
- [x] https://github.com/weaviate/weaviate-swagger/issues/57
- [x] https://github.com/weaviate/weaviate-swagger/issues/59

**Comment by bobvanluijt** [comment]
@johnciocoiu it is "Do" not "Make" a new release ;-)

**Comment by bobvanluijt** [comment]
Done: https://github.com/weaviate/weaviate-swagger/releases/tag/v0.2.4
