### ISSUE TITLE
Review the Event endpoints

### ISSUE THREAD

**Issue by johnciocoiu** [weaviate/weaviate-swagger#55]
- [x] ThingID is missing in the event-endpoints. Add it.
- [ ] Two ID's are used, EventID and ThingID (for thing-events). The database now can not handle queries on two unique Id's. @bobvanluijt: Think about how to fix this. One way is to remove the thingId/groupId from the URL, and add them in the body.

**Comment by bobvanluijt** [comment]
@johnciocoiu Resolve like this:

When an event is created, _inside the object_ there is an `eventId` the events gets the UUID of the Thing and the RefType `#/paths/events`

Query example: `/things/{thingId}/events/{eventId}`;
1. Look for the `thingId` in UUID with `refType` = `#/paths/events`.
2. Loop through results with `CreateTimeMs` ascending until the `eventId` is found.
