### ISSUE TITLE
Add schema to commands & events and rename commands to Actions

### ISSUE THREAD

**Issue by bobvanluijt** [weaviate/weaviate-swagger#92]
Add Schema definition to Actions. This is alread done for things;
1. https://github.com/weaviate/weaviate-swagger/blob/develop/weaviate-swagger.json#L925
2. https://github.com/weaviate/weaviate-swagger/blob/develop/weaviate-swagger.json#L910

**Comment by johnciocoiu** [comment]
Won't fix, wil be fixed in #97.
